### ISSUE TITLE
Crash version 1.2.3 mc 1.20.1

### ISSUE THREAD

**Issue by Felisinnn** [AdamRaichu/suppress-OpenGL-1280#7]
https://mclo.gs/yyMM6jG 
If the mod is disabled the pack runs fine

**Comment by AdamRaichu** [comment]
Thanks for reporting this! I should be able to fix it by reverting to java 17 in my build process. (Explanation below for those who are curious.)

Here are the relevant error messages from the log:

```
[01:45:06] [Render thread/ERROR]: Mod suppressopengl1280 provides a broken implementation of ModMenuApi
--
2202 | java.lang.UnsupportedClassVersionError: io/github/adamraichu/suppressopengl1280/ModMenuIntegration has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
2203 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
2204 | at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
2205 | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
2206 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
2207 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
2208 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
2209 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
2210 | at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
2211 | at java.lang.Class.forName0(Native Method) ~[?:?]
2212 | at java.lang.Class.forName(Class.java:467) ~[?:?]
2213 | at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.11.jar:?]
2214 | at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.11.jar:?]
2215 | at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.11.jar:?]
2216 | at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:74) ~[modmenu-7.2.2.jar:?]
2217 | at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
2218 | at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:70) ~[modmenu-7.2.2.jar:?]
2219 | at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
2220 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.15.11.jar:?]
2221 | at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9) ~[notenoughcrashes-4.4.7 1.20.1-fabric.jar:?]
2222 | at net.minecraft.client.MinecraftClient.redirect$mkm000$notenoughcrashes$catchFabricInit(MinecraftClient.java:54032) ~[client-intermediary.jar:?]
2223 | at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458) ~[client-intermediary.jar:?]
2224 | at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
2225 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
2226 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
2227 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
2228 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
2229 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
2230 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]


[TRUNCATED]


[01:45:09] [Render thread/ERROR]: Minecraft has crashed!
--
2436 | net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/client/gl/GlDebug has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
2437 | at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
2438 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
2439 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
2440 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
2441 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
2442 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
2443 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
2444 | Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/client/gl/GlDebug has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
2445 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
2446 | at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
2447 | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
2448 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
2449 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
2450 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
2451 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
2452 | at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
2453 | at net.minecraft.client.MinecraftClient.method_37289(MinecraftClient.java:2429) ~[client-intermediary.jar:?]
2454 | at net.minecraft.util.SystemDetails.addSection(SystemDetails.java:66) ~[client-intermediary.jar:?]
2455 | at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient.java:2429) ~[client-intermediary.jar:?]
2456 | at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient.java:2419) ~[client-intermediary.jar:?]
2457 | at net.minecraft.client.main.Main.main(Main.java:220) ~[minecraft-1.20.1-client.jar:?]
2458 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
2459 | ... 5 more
2460 | Process exited with code 1.
2461 | Log upload triggered at: 02 Sep 2024 01:45:36  0200
```

Apparently, it seems like the Java installation decided my mod was "too new". The fix would be to change the build process to use Java 17 (what it was before) instead of 21 (which Minecraft theoretically requires as of 1.21).

**Comment by AdamRaichu** [comment]
I'm closing this issue because I think I fixed it, but let me know if you're still having trouble.
